# pylint: disable = unspecified-encoding
#  sfzen/utils/compile_syntax.py
#
#  Copyright 2024 Leon Dionne <ldionne@dridesign.sh.cn>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
"""
This utility uses the yaml parser to parse the SFZ defintion and create the
OPCODES dictionary, used throughout.
"""
from importlib import import_module
from re import compile as rcompile
from pathlib import Path
from repr_soso import Repr
import yaml
import sfzen
from sfzen import (
	LOG_FORMAT, INT_VALIDATOR_REGEX,
	K_CATEGORY, K_NAME, K_ID, K_VERSION, K_DESCRIPTION, K_MODULATES, K_MOD_TYPE,
	K_ALIASES, K_INDEXED, K_VALUE, K_VAR_TYPE, K_UNIT, K_DEFAULT, K_MIN, K_MAX,
	K_CHOICES
)

K_CATEGORIES	= 'categories'
K_TYPES			= 'types'
K_OPCODES		= 'opcodes'
K_SHORT_DESC	= 'short_description'
K_MODULATION	= 'modulation'
K_ALIAS			= 'alias'
K_INDEX			= 'index'
K_TYPE_NAME		= 'type_name'
K_OPTIONS		= 'options'

VERSION_MAP = {
	None				: None,
	'SFZ v1'			: 'v1',
	'SFZ v2'			: 'v2',
	'ARIA'				: 'aria',
	'LinuxSampler'		: 'linuxsampler',
	'Cakewalk'			: 'cakewalk',
	'Cakewalk SFZ v2'	: 'cakewalk_v2'
}

VAR_TYPE_MAP = {
	'string'	: 'str',
	'integer'	: 'int',
	'float'		: 'float'
}

UNK_CATEGORIES = {
	"Sound Source"				: "src",
	"Region Logic"				: "regl",
	"Performance Parameters"	: "perf",
	"Modulation"				: "mod"
}

STRIP_HTML_REGEX = rcompile('<[^>]+>')

HEADER = """# pylint: skip-file
\"\"\"
Automatically generated by "compile_syntax.py".
DO NOT EDIT
\"\"\"

"""


def compile_syntax(source_file, target_file):
	print(f'Reading "{source_file}" ...')
	with open(source_file) as ymlfile:
		syntax = yaml.load(ymlfile, Loader = yaml.SafeLoader)
	with open(target_file, 'w') as pyfile:
		pyfile.write(HEADER)
		pyfile.write('SYNTAX = ')
		Repr(syntax).write(pyfile)
		pyfile.write("\n")
	print(f'Wrote "{target_file}"')
	return syntax

def compile_opcodes(syntax, target_file):
	categories = {}
	for cat in syntax[K_CATEGORIES]:
		cat_id = cat[K_ID] if K_ID in cat else UNK_CATEGORIES[cat[K_NAME]]
		categories[cat_id] = {
			K_ID			: cat_id,
			K_NAME			: cat[K_NAME],
			K_DESCRIPTION	: cat.get(K_SHORT_DESC, ""),
			K_CATEGORY		: None
		}
		if types := cat.get(K_TYPES):
			for typ in types:
				categories[typ[K_ID]] = {
					K_ID			: typ[K_ID],
					K_NAME			: typ[K_NAME],
					K_DESCRIPTION	: typ.get(K_SHORT_DESC, ""),
					K_CATEGORY		: cat_id
				}
	opcodes = {
		opcode[K_NAME]: opcode \
		for opcode in extract_opcodes(syntax[K_CATEGORIES])
	}
	def _override(opcode, key, value):
		print(f'Overriding "{opcode[K_NAME]}.{key}" ({opcode[K_VALUE][key]}) with "{value}"')
		opcode[K_VALUE][key] = value
	for opcode in opcodes.values():
		if K_VALUE in opcode:
			if opcode[K_VALUE][K_DEFAULT] is not None:
				if opcode[K_VALUE][K_VAR_TYPE] == 'float':
					try:
						float(opcode[K_VALUE][K_DEFAULT])
					except ValueError:
						_override(opcode, K_DEFAULT, None)
				elif opcode[K_VALUE][K_VAR_TYPE] == 'int' and \
					not isinstance(opcode[K_VALUE][K_DEFAULT], int) and \
					not bool(INT_VALIDATOR_REGEX.match(opcode[K_VALUE][K_DEFAULT])):
					_override(opcode, K_DEFAULT, None)
			if opcode[K_VALUE][K_MAX] == 'SampleRate / 2':
				_override(opcode, K_MAX, None)
	_override(opcodes['loop_mode'], K_DEFAULT, 'no_loop')
	_override(opcodes['amp_velcurve_N'], K_DEFAULT, None)
	_override(opcodes['eqN_freq'], K_DEFAULT, None)

	with open(target_file, 'w') as pyfile:
		pyfile.write(HEADER)
		pyfile.write('CATEGORIES = ')
		Repr(categories).write(pyfile)
		pyfile.write("\n\n")
		pyfile.write('OPCODES = ')
		Repr(opcodes).write(pyfile)
		pyfile.write("\n\n")
	print(f'Wrote "{target_file}"')

def version_code(version):
	return VERSION_MAP.get(version)

def value_dict(src_dict):
	if src_dict is None:
		return {
			K_VAR_TYPE		: None,
			K_UNIT			: None,
			K_DEFAULT		: None,
			K_MIN			: None,
			K_MAX			: None,
			K_CHOICES		: []
		}
	def choice_list(choices):
		return [] if choices is None else [ {
			K_NAME			: option.get(K_NAME),
			K_DESCRIPTION	: option.get(K_DESCRIPTION),
			K_VERSION		: version_code(option.get(K_VERSION))
		} for option in choices ]
	return {
		K_VAR_TYPE		: VAR_TYPE_MAP.get(src_dict.get(K_TYPE_NAME)),
		K_UNIT			: src_dict.get(K_UNIT),
		K_DEFAULT		: src_dict.get(K_DEFAULT),
		K_MIN			: src_dict.get(K_MIN),
		K_MAX			: src_dict.get(K_MAX),
		K_CHOICES		: choice_list(src_dict.get(K_OPTIONS))
	}

def extract_modulation(cat_id, items, modulates):
	for mod_type, modulations in items:
		if isinstance(modulations, list):  # some are just checkmarks
			for mod in modulations:
				yield from extract_opcode(mod, cat_id, modulates, mod_type)

def extract_opcode(src_dict, cat_id, modulates, mod_type):
	opcode_data = {
		K_NAME			: src_dict[K_NAME],
		K_VERSION		: version_code(src_dict.get(K_VERSION)),
		K_ALIASES		: None,
		K_CATEGORY		: cat_id,
		K_DESCRIPTION	: STRIP_HTML_REGEX.sub('', src_dict.get(K_SHORT_DESC, '')),
		K_MODULATES		: modulates,
		K_MOD_TYPE		: mod_type,
		K_INDEXED		: K_INDEX in src_dict,
		K_VALUE			: value_dict(src_dict.get(K_VALUE))
	}
	yield opcode_data
	for alias in src_dict.get(K_ALIAS, []):
		alias_meta = {
			K_NAME		: alias[K_NAME],
			K_VERSION	: version_code(alias.get(K_VERSION, opcode_data[K_VERSION])),
			K_ALIASES	: src_dict[K_NAME]
		}
		yield alias_meta
		if K_MODULATION in alias:
			yield from extract_modulation(
				cat_id,
				alias[K_MODULATION].items(),
				alias[K_NAME])
	if K_MODULATION in src_dict:
		yield from extract_modulation(
			cat_id,
			src_dict[K_MODULATION].items(),
			src_dict[K_NAME])

def extract_opcodes(list_):
	for item in list_:
		if cat_id := item.get(K_ID):
			for opcode in item[K_OPCODES]:
				yield from extract_opcode(opcode, cat_id, None, None)
		if types := item.get(K_TYPES):
			yield from extract_opcodes(types)


if __name__ == "__main__":
	utils_path = Path(__file__).parent
	yaml_path = utils_path.joinpath('res', 'syntax.yml')
	syntax_path = utils_path.joinpath('res', 'syntax.py')

	app_path = Path(sfzen.__file__).parent
	opcodes_path = app_path.joinpath('opcodes.py')

	syntax = compile_syntax(yaml_path, syntax_path)
	compile(syntax_path.read_text(), syntax_path.name, 'exec')
	print(f'Successfully compiled "{syntax_path}"')

	compile_opcodes(syntax, opcodes_path)
	from sfzen import opcodes
	print('Successfully imported sfzen.opcodes')


#  end sfzen/utils/compile_syntax.py
